/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_A.h"
#include "Clock_1.h"
#include "PWM_B.h"
#include "Clock_2.h"
#include "PWM_C.h"
#include "Clock_3.h"
#include "A.h"
#include "A_aliases.h"
#include "B.h"
#include "B_aliases.h"
#include "C.h"
#include "C_aliases.h"
#include "INHA.h"
#include "INHA_aliases.h"
#include "INHB.h"
#include "INHB_aliases.h"
#include "INHC.h"
#include "INHC_aliases.h"
#include "u.h"
#include "u_aliases.h"
#include "v.h"
#include "v_aliases.h"
#include "w.h"
#include "w_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "CTRL.h"
#include "CTRL_aliases.h"
#include "Clock_micros.h"
#include "Counter_micros.h"
#include "isr_millis.h"
#include "isr_uf.h"
#include "isr_vf.h"
#include "isr_wf.h"
#include "isr_wr.h"
#include "isr_vr.h"
#include "isr_ur.h"
#include "Blue.h"
#include "Blue_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

